// Every word the console shows, in one place, so it can be translated (e.g. to Greek) later.
// `t` is the owner's console (English). `client` is what clients see: the delivery page and
// the weekly email (Greek). Placeholders like {name} are filled with fmt().

export function fmt(text: string, vars: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

export const t = {
  brand: "tapesway",
  consoleName: "Console",
  sample: "Sample",
  sampleHint: "Sample data for the demo",
  demoBadge: "Demo mode",
  demoBadgeHint: "Data is stored in a local file and emails go to the Outbox. Connect Supabase and Resend to go live.",
  soon: "Soon",
  none: "–",
  save: "Save",
  cancel: "Cancel",
  back: "Back",
  edit: "Edit",
  view: "View",
  open: "Open",
  copy: "Copy",
  copied: "Copied",
  search: "Search",
  all: "All",
  week: "Week",
  thisWeek: "this week",
  nextWeek: "next week",
  lastWeek: "last week",
  signOut: "Sign out",
  menu: "Menu",

  nav: {
    overview: "Overview",
    leads: "Leads",
    clients: "Clients",
    jobs: "Generate",
    review: "Review",
    deliveries: "Deliveries",
    outbox: "Outbox (demo)",
    payments: "Payments",
    trends: "Trends",
    analytics: "Analytics",
    later: "Later",
  },

  login: {
    title: "Sign in",
    lead: "The tapesway console is private.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    wrong: "That didn't work. Check the details and try again.",
    notOwner: "This account is not allowed into the console.",
    tooMany: "Too many attempts. Wait a few minutes and try again.",
    devHint: "Local demo: the password is “demo” (set CONSOLE_PASSWORD to change it).",
  },

  overview: {
    title: "Overview",
    newLeads: "New leads",
    awaitingReview: "Awaiting review",
    activeClients: "Active clients",
    thisWeek: "This week",
    generated: "Generated",
    approved: "Approved",
    sent: "Sent",
    ofClients: "of {n} active clients",
    recent: "Recent activity",
    noActivity: "Nothing yet. New leads, generations and deliveries will show up here.",
    goLeads: "Open leads",
    goReview: "Open review",
    goClients: "Open clients",
    removeSample: "Remove sample data",
    removeSampleHint: "The demo starts with sample leads and clients so every page has something to show. Remove them when you start adding real ones.",
    removeSampleConfirm: "Remove all sample records?",
    sampleRemoved: "Sample data removed.",
  },

  leads: {
    title: "Leads",
    lead: "Every message from the website form lands here.",
    empty: "No leads here yet. Messages from the website form will appear here.",
    colName: "Name",
    colBusiness: "Business",
    colIsland: "Island",
    colType: "Type",
    colStatus: "Status",
    colReceived: "Received",
    message: "Message",
    email: "Email",
    source: "Source",
    status: "Status",
    updateStatus: "Update status",
    statusSaved: "Status updated.",
    convert: "Convert to client",
    convertedTo: "Client created:",
    reply: "Reply by email",
    statuses: { new: "New", contacted: "Contacted", proposal: "Proposal", won: "Won", lost: "Lost" },
  },

  clients: {
    title: "Clients",
    lead: "Select one, several or all clients, then generate the week in one go.",
    add: "Add client",
    empty: "No clients yet. Add one, or convert a lead.",
    noMatch: "No clients match.",
    searchPlaceholder: "Search name, island, type, email",
    filterStatus: "Status",
    filterIsland: "Island",
    anyIsland: "All islands",
    colClient: "Client",
    colIsland: "Island",
    colType: "Type",
    colLanguages: "Languages",
    colPlan: "Plan",
    colStatus: "Status",
    colWeek: "This week",
    selectAll: "Select all shown",
    selectRow: "Select {name}",
    selected: "{n} selected",
    clear: "Clear",
    generate: "Generate this week",
    generateWeek: "Generate {week}",
    generating: "Queuing…",
    regenerate: "Regenerate if already generated",
    regenerateHint: "Replaces that week's drafts, including approved ones.",
    weekLabel: "Week",
    statuses: { active: "Active", paused: "Paused" },
    weekState: {
      none: "Not generated",
      generating: "Generating",
      review: "In review {a}/{n}",
      approved: "Approved",
      sent: "Sent",
      failed: "Failed",
    },
    newTitle: "New client",
    editTitle: "Edit {name}",
    fromLead: "Filled in from the lead by {name}. Check and complete the details.",
    created: "Client added.",
    saved: "Changes saved.",
    detail: {
      contact: "Contact",
      business: "Business",
      brief: "Brief",
      weeks: "Weeks",
      noWeeks: "Nothing generated yet.",
      generateThis: "Generate {week}",
      regenerateWeek: "Regenerate week",
      regenerateConfirm: "Replace this week's drafts, including approved ones?",
      review: "Review",
      delivery: "Delivery",
      items: "Items",
      fromLead: "Created from a lead",
      notes: "Notes",
    },
    form: {
      sectionBusiness: "Business",
      sectionContact: "Contact",
      sectionBrief: "Content brief",
      sectionAccount: "Account",
      business_name: "Business name",
      contact_name: "Contact name",
      email: "Email",
      emailHint: "The week's pack is sent here.",
      phone: "Phone",
      island: "Island",
      business_type: "Business type",
      businessTypeHint: "For example villa, boutique hotel, restaurant, beach bar, boat tours.",
      languages: "Languages",
      languagesHint: "Captions are written in each of these.",
      tone_of_voice: "Tone of voice",
      tonePlaceholder: "Calm, understated luxury",
      audience: "Audience",
      audiencePlaceholder: "Who the videos are for",
      dos: "Do's",
      donts: "Don'ts",
      links: "Links",
      linksHint: "Website, Instagram, TikTok, Google Maps. One per line.",
      plan: "Plan",
      status: "Status",
      notes: "Notes (private)",
      required: "Required",
      invalidEmail: "Enter a valid email address.",
      needLanguage: "Choose at least one language.",
      fixErrors: "Please fix the highlighted fields.",
      submitNew: "Add client",
      submitEdit: "Save changes",
    },
    langs: { EN: "English", DE: "German", FR: "French", EL: "Greek" },
  },

  jobs: {
    title: "Generate",
    lead: "Generation runs as a queue, a couple of clients at a time. You can leave this page; it carries on.",
    empty: "No generation jobs yet. Select clients on the Clients page and press Generate this week.",
    queued: "Queued",
    generating: "Generating",
    ready: "Ready",
    failed: "Failed",
    retry: "Retry",
    progress: "{done} of {total} done",
    batch: "Batch",
    colClient: "Client",
    colWeek: "Week",
    colKind: "Job",
    colStatus: "Status",
    colTime: "Queued",
    kindWeek: "Week's drafts",
    kindWeekRegen: "Week's drafts (regenerate)",
    kindItem: "Redo one item",
    queuedSummary: "{n} queued.",
    skippedGenerated: "{n} skipped: already generated this week (tick “Regenerate” to replace).",
    skippedProgress: "{n} skipped: already in progress.",
    skippedPaused: "{n} skipped: paused.",
    nothingSelected: "Select at least one client.",
    toReview: "Go to review",
    live: "Updating live",
    generatorNote: "Generator: demo (text drafts, no video file yet).",
  },

  review: {
    title: "Review",
    lead: "Nothing goes to a client until you approve it.",
    empty: "Nothing waiting for review.",
    filterPending: "To review",
    filterChanges: "Being redone",
    filterApproved: "Approved",
    approve: "Approve",
    approved: "Approved",
    approveAll: "Approve all {n} for this client",
    requestChanges: "Request changes",
    notesLabel: "What should change?",
    notesPlaceholder: "e.g. Less text on screen, show the pool at sunset instead",
    sendBack: "Send back for regeneration",
    notesRequired: "Write a note so the generator knows what to change.",
    redoing: "Being regenerated with your notes…",
    lastNotes: "Your notes",
    version: "v{n}",
    script: "Script",
    captions: "Captions",
    hashtags: "Hashtags",
    media: "Video",
    mediaPlaceholder: "Demo: no video file yet",
    aiReview: "AI review",
    aiNotSetUp: "AI review: not set up yet",
    ai: { green: "Pass", yellow: "Probably fine: your call", red: "Regenerate" },
    readyToSend: "All approved. Ready to send.",
    goDeliveries: "Go to deliveries",
    weekOf: "{week} · {range}",
  },

  deliveries: {
    title: "Deliveries",
    lead: "When every item of a client's week is approved, send the week's pack: an email with a private link to the videos, captions and hashtags.",
    empty: "Nothing to deliver yet. Generate and approve a week first.",
    colClient: "Client",
    colWeek: "Week",
    colItems: "Approved",
    colStatus: "Status",
    colActions: "",
    notReady: "Not ready",
    ready: "Ready to send",
    sent: "Sent {when}",
    opened: "Opened {when}",
    notOpened: "Not opened yet",
    downloads: "Downloads: {n}",
    send: "Send week's pack",
    resend: "Send again",
    sending: "Sending…",
    preview: "Preview page",
    copyLink: "Copy link",
    sentOk: "Week's pack sent.",
    noEmail: "This client has no email address. Add one first.",
    notAllApproved: "Every item must be approved first.",
    sendFailed: "The email could not be sent. Check the email settings (RESEND_API_KEY, EMAIL_FROM) and try again.",
    showAll: "All weeks",
    showThis: "This week",
  },

  outbox: {
    title: "Outbox (demo)",
    lead: "In demo mode no email leaves this computer. Every email the console would send is kept here.",
    liveNote: "Emails are sent with Resend. This is a copy of what was sent.",
    empty: "No emails yet.",
    to: "To",
    from: "From",
    kind: "Type",
    kinds: { lead_alert: "New lead alert", weekly_pack: "Week's pack" } as Record<string, string>,
    showHtml: "Show email as sent",
  },

  soonPage: {
    payments: "Payments with Stripe: plans, invoices and payment status per client.",
    trends: "Weekly trends and viral UGC ideas to feed the generator.",
    analytics: "Analytics overall and per client.",
  },

  activityTime: {
    justNow: "just now",
    minutes: "{n} min ago",
    hours: "{n} h ago",
    days: "{n} d ago",
  },

  emails: {
    leadSubject: "New lead: {name}{business}",
    leadIntro: "A new message came in through the website form.",
    leadOpen: "Open in the console",
    fields: { name: "Name", business: "Business", email: "Email", island: "Island", type: "Type", message: "Message" },
  },

  errors: {
    notFound: "Not found.",
    generic: "Something went wrong. Try again.",
  },
};

// Client-facing text (Greek): the delivery page and the weekly email.
export const client = {
  pageTitle: "Το περιεχόμενο της εβδομάδας",
  intro: "Τα βίντεο της εβδομάδας για {business}, μαζί με τις λεζάντες και τα hashtags. Κατεβάστε τα και δημοσιεύστε τα όποτε σας βολεύει.",
  week: "Εβδομάδα {range}",
  video: "Βίντεο {n}",
  caption: "Λεζάντα",
  hashtags: "Hashtags",
  copy: "Αντιγραφή",
  copied: "Αντιγράφηκε",
  copyAll: "Αντιγραφή λεζάντας και hashtags",
  download: "Λήψη βίντεο",
  downloadText: "Λήψη κειμένων",
  noVideo: "Demo: δεν υπάρχει ακόμη αρχείο βίντεο",
  langs: { EN: "Αγγλικά", DE: "Γερμανικά", FR: "Γαλλικά", EL: "Ελληνικά" },
  footer: "Για οτιδήποτε χρειαστείτε, απαντήστε στο email μας.",
  notFoundTitle: "Ο σύνδεσμος δεν βρέθηκε",
  notFoundText: "Ο σύνδεσμος μπορεί να έχει αλλάξει. Επικοινωνήστε μαζί μας για έναν νέο.",
  preview: "Προεπισκόπηση από την κονσόλα: δεν καταγράφεται ως άνοιγμα.",
  email: {
    subject: "Το περιεχόμενο της εβδομάδας είναι έτοιμο – {business}",
    greeting: "Γεια σας{name},",
    body: "Τα βίντεο της εβδομάδας ({range}) είναι έτοιμα. Θα τα βρείτε μαζί με τις λεζάντες και τα hashtags στον παρακάτω σύνδεσμο:",
    button: "Δείτε το περιεχόμενο",
    after: "Μπορείτε να τα κατεβάσετε και να τα δημοσιεύσετε όποτε σας βολεύει.",
    signoff: "Η ομάδα της tapesway",
  },
};
